name: json_to_model
description: Generate model class from Json file. Based from fadhilx's json_to_model.
version: 2.1.0
homepage: https://github.com/idabgsram/json_to_model

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  path: ^1.9.0

  args: ^2.5.0
  build_runner_core: ^7.3.1

  io: ^1.0.4
  logging: ^1.2.0

  expressions: 
      git:
        url: https://github.com/idabgsram/expressions
  build_runner: ^2.4.11

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
