name: json_to_model
description: Generate model class from Json file. Based from fadhilx's json_to_model.
version: 2.0.2
homepage: https://github.com/idabgsram/json_to_model

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0

  args: ^2.0.0
  build_runner_core: ^7.0.0

  io: ^1.0.3
  logging: ^1.0.1

  expressions: ^0.2.3
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  json_annotation: ^4.0.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
