name: json_to_model
description: Generate model class from Json file. Based from fadhilx's json_to_model.
version: 2.0.6+1
homepage: https://github.com/idabgsram/json_to_model

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.1

  args: ^2.3.1
  build_runner_core: ^7.2.3

  io: ^1.0.3
  logging: ^1.0.2

  expressions: 
      git:
        url: https://github.com/idabgsram/expressions
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.3
